spring.application.name=SmartExpenseTracker

spring.datasource.url = jdbc:mysql://localhost:3306/expense_tracker_application
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

server.port = 8082

logging.level.org.hibernate.SQL = debug
logging.level.org.springframework.security = debug

logging.level.root=Info
logging.level.com.ganesh.expensetracker = DEBUG

# console log format with correlation ID
logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] [%level] %logger{36} - %msg%n


spring.jpa.open-in-view = false

# API base URL
server.servlet.context-path = /api/v1

# JWT Configuration
# Jwt Secret Key (key = expense-tracker-authentication-secret-key-very-secure)
jwt.secret = c12a1fb8cb05f73c56d5403030437b0b3b83688fb676e4960e64ce62e6ec14f4

# Jwt Token Expiration (15 minutes)
jwt.expiration = 900000


# Admin credentials
app.admin.email = admin@gmail.com
app.admin.password = admin@123
app.init.enabled = true


# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379